name: "Lint, Build & Test"
on:
  pull_request:
    branches:
    - main
jobs:
  test-source:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
      - run: npm run build
      - run: npm run test-ci
