name: "Manual: Lint, Build & Test"
on:
  workflow_dispatch:
    
jobs:
  test-source:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
      - run: npm run build
      - run: npm run test-ci
